"""Shared service endpoint and message contracts."""

from deckr.contracts.lanes import SERVICE_LANE_CONTRACT
from deckr.services.client import DeckrServices
from deckr.services.messages import (
    SERVICE_REPLY,
    SERVICE_REQUEST,
    ServiceError,
    ServiceMessageBody,
    ServiceReplyBody,
    ServiceReplyStatus,
    ServiceRequestBody,
    service_body,
    service_body_for_type,
    service_message,
    service_message_schema,
    service_reply_message,
    service_request_message,
)
from deckr.services.runtime import (
    AuthorizedServiceRequest,
    ServiceAdvertisementPayload,
    ServiceBackendStatus,
    ServiceDescriptor,
    ServiceProtocol,
    ServiceUnavailable,
    ServiceUseAuthorizationError,
    ServiceUseLease,
    ServiceViewFamily,
    ServiceViewFamilyDefinition,
    ServiceViewRef,
    UnsupportedServiceScope,
    authorize_service_request,
    newest_service_descriptor,
    parse_service_descriptor,
    service_descriptor_sort_key,
    service_reply_ends_service_use,
    service_unavailable_ends_service_use,
    service_view_key,
    service_view_prefix,
)
from deckr.services.subscriptions import (
    ResourceSubscriptionSession,
    ServiceSubscriptionMessage,
    ServiceSubscriptionState,
    SharedResourceSubscriptionManager,
)
from deckr.services.views import ServiceViewChange, ServiceViewEntry, ServiceViewStore

__all__ = [
    "SERVICE_REQUEST",
    "SERVICE_REPLY",
    "SERVICE_LANE_CONTRACT",
    "AuthorizedServiceRequest",
    "DeckrServices",
    "ServiceAdvertisementPayload",
    "ServiceBackendStatus",
    "ServiceRequestBody",
    "ServiceReplyBody",
    "ServiceReplyStatus",
    "ServiceDescriptor",
    "ServiceError",
    "ServiceMessageBody",
    "ServiceProtocol",
    "ServiceSubscriptionMessage",
    "ServiceSubscriptionState",
    "ServiceUnavailable",
    "ServiceUseAuthorizationError",
    "ServiceUseLease",
    "ServiceViewChange",
    "ServiceViewEntry",
    "ServiceViewFamily",
    "ServiceViewFamilyDefinition",
    "ServiceViewRef",
    "ServiceViewStore",
    "SharedResourceSubscriptionManager",
    "UnsupportedServiceScope",
    "ResourceSubscriptionSession",
    "authorize_service_request",
    "newest_service_descriptor",
    "parse_service_descriptor",
    "service_body",
    "service_body_for_type",
    "service_reply_ends_service_use",
    "service_request_message",
    "service_reply_message",
    "service_descriptor_sort_key",
    "service_message",
    "service_message_schema",
    "service_unavailable_ends_service_use",
    "service_view_key",
    "service_view_prefix",
]
