"""Shared service endpoint and message contracts."""

from deckr.services.messages import (
    SERVICE_COMMAND,
    SERVICE_COMMAND_REPLY,
    ServiceCommandBody,
    ServiceCommandReplyBody,
    ServiceCommandStatus,
    ServiceError,
    ServiceMessageBody,
    service_body,
    service_body_for_type,
    service_command_message,
    service_command_reply_message,
    service_message,
    service_message_schema,
)
from deckr.services.runtime import (
    GenericService,
    ServiceAdvertisement,
    ServiceAdvertisementPayload,
    ServiceBackendStatus,
    ServiceClient,
    ServiceProtocol,
    ServiceUseTerms,
    ServiceViewFamily,
    ServiceViewRef,
    service_advertisement_from_candidate,
    service_use_terms,
    service_view_key,
    service_view_prefix,
)

__all__ = [
    "GenericService",
    "SERVICE_COMMAND",
    "SERVICE_COMMAND_REPLY",
    "ServiceAdvertisement",
    "ServiceAdvertisementPayload",
    "ServiceBackendStatus",
    "ServiceClient",
    "ServiceCommandBody",
    "ServiceCommandReplyBody",
    "ServiceCommandStatus",
    "ServiceError",
    "ServiceMessageBody",
    "ServiceProtocol",
    "ServiceUseTerms",
    "ServiceViewFamily",
    "ServiceViewRef",
    "service_advertisement_from_candidate",
    "service_body",
    "service_body_for_type",
    "service_command_message",
    "service_command_reply_message",
    "service_message",
    "service_message_schema",
    "service_use_terms",
    "service_view_key",
    "service_view_prefix",
]
