"""Shared service endpoint and message contracts."""

from deckr.services.messages import (
    SERVICE_COMMAND,
    SERVICE_COMMAND_REPLY,
    ServiceCommandBody,
    ServiceCommandReplyBody,
    ServiceCommandStatus,
    ServiceError,
    ServiceMessageBody,
    service_body,
    service_body_for_type,
    service_command_message,
    service_command_reply_message,
    service_message,
    service_message_schema,
)
from deckr.services.runtime import (
    ServiceAdvertisementPayload,
    ServiceBackendStatus,
    ServiceDescriptor,
    ServiceProtocol,
    ServiceUnavailable,
    ServiceUseLease,
    ServiceUseRequest,
    ServiceUseTerms,
    ServiceViewFamily,
    ServiceViewRef,
    UnsupportedServiceScope,
    newest_service_descriptor,
    parse_service_descriptor,
    service_descriptor_sort_key,
    service_use_terms,
    service_view_key,
    service_view_prefix,
)
from deckr.services.views import ServiceViewChange, ServiceViewEntry, ServiceViewStore

__all__ = [
    "SERVICE_COMMAND",
    "SERVICE_COMMAND_REPLY",
    "ServiceAdvertisementPayload",
    "ServiceBackendStatus",
    "ServiceCommandBody",
    "ServiceCommandReplyBody",
    "ServiceCommandStatus",
    "ServiceDescriptor",
    "ServiceError",
    "ServiceMessageBody",
    "ServiceProtocol",
    "ServiceUnavailable",
    "ServiceUseLease",
    "ServiceUseRequest",
    "ServiceUseTerms",
    "ServiceViewChange",
    "ServiceViewEntry",
    "ServiceViewFamily",
    "ServiceViewRef",
    "ServiceViewStore",
    "UnsupportedServiceScope",
    "newest_service_descriptor",
    "parse_service_descriptor",
    "service_body",
    "service_body_for_type",
    "service_command_message",
    "service_command_reply_message",
    "service_descriptor_sort_key",
    "service_message",
    "service_message_schema",
    "service_use_terms",
    "service_view_key",
    "service_view_prefix",
]
