from types import SimpleNamespace
from typing import Any, Protocol

from deckr.plugin.events import (
    DialRotate,
    KeyDown,
    KeyUp,
    TouchSwipe,
    TouchTap,
    WillAppear,
    WillDisappear,
)
from invariant import Node, SubGraphNode


class ControlContext(Protocol):
    async def on_will_appear(self): ...
    async def on_will_disappear(self): ...
    async def on_key_up(self, event: KeyUp): ...
    async def on_key_down(self, event: KeyDown): ...
    async def on_dial_rotate(self, event: DialRotate): ...
    async def on_touch_tap(self, event: TouchTap): ...
    async def on_touch_swipe(self, event: TouchSwipe): ...


class PluginContext(Protocol):
    """Context passed to plugin actions."""

    # Elgato API
    async def set_title(self, text: str): ...
    async def set_image(self, image: str): ...
    async def set_state(self, state: int): ...
    async def show_alert(self, *, slot: str | None = None): ...
    async def show_ok(self, *, slot: str | None = None): ...
    async def get_settings(self) -> SimpleNamespace: ...
    async def set_settings(self, settings: dict): ...
    async def open_url(self, url: str): ...
    async def switch_to_profile(
        self,
        *,
        profile: str = "default",
        page: int = 0,
    ) -> None: ...

    # deckr extensions
    async def set_key_image(self, graph: Node | SubGraphNode): ...
    async def open_page(self, descriptor: Any) -> None: ...
    async def close_page(self) -> None: ...
    async def sleep_screen(self): ...
    async def wake_screen(self): ...


class PluginAction(Protocol):
    """Protocol for plugin actions.

    Actions may have manifest_state_defaults (dict[int, StateOverride] | None) set by
    the plugin provider for render resolution. Use getattr(action, "manifest_state_defaults", None).
    """

    uuid: str

    async def on_will_appear(self, event: WillAppear, context: PluginContext): ...
    async def on_will_disappear(self, event: WillDisappear, context: PluginContext): ...
    async def on_key_up(self, event: KeyUp, context: PluginContext): ...
    async def on_key_down(self, event: KeyDown, context: PluginContext): ...

    # Optional: on_touch_tap(event: TouchTap, context: PluginContext)
    # Optional: on_touch_swipe(event: TouchSwipe, context: PluginContext)
    # Optional: on_page_appear(event: PageAppear, context: PluginContext)
    # Optional: on_page_disappear(event: PageDisappear, context: PluginContext)


class Plugin(Protocol):
    """Protocol for individual plugins loaded by a provider (e.g. clock, sonos)."""

    async def provides_actions(self) -> list[str]: ...
    async def get_action(self, uuid: str) -> PluginAction | None: ...
